version: "3"
services:
  app:
    container_name: dockerTesteGlobo
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/app
    links:
      - mongo
      - web
  mongo:
    container_name: mongoDB_testeGlobo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  web:
    stdin_open: true # docker run -i
    tty: true
    container_name: frontTeste
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/app'
    ports:
      - 3001:3000
